CREATE TABLE `data_platform_freight_agreement_item_data`
(
    `FreightAgreement`                                  int(16) NOT NULL,
    `FreightAgreementItem`                              int(6) NOT NULL,
    `FreightAgreementItemCategory`                      varchar(4) NOT NULL,
    `SupplyChainRelationshipID`                         int(16) NOT NULL,
    `SupplyChainRelationshipDeliveryID`                 int(6) DEFAULT NULL,
    `SupplyChainRelationshipDeliveryPlantID`            int(4) DEFAULT NULL,
    `FreightAgreementItemText`                          varchar(200) NOT NULL,
    `Product`                                           varchar(40) NOT NULL,
    `ProductStandardID`                                 varchar(18) NOT NULL,
    `ProductGroup`                                      varchar(9) DEFAULT NULL,
    `BaseUnit`                                          varchar(3) NOT NULL,
    `DeliverToParty`                                    int(12) DEFAULT NULL,
    `DeliverFromParty`                                  int(12) DEFAULT NULL,
    `CreationDate`                                      date NOT NULL,
    `LastChangeDate`                                    date NOT NULL,
    `DeliverToPlant`                                    varchar(4) DEFAULT NULL,
    `DeliverToPlantTimeZone`                            varchar(3) DEFAULT NULL,
    `DeliverFromPlant`                                  varchar(4) DEFAULT NULL,
    `DeliverFromPlantTimeZone`                          varchar(3) DEFAULT NULL,
    `Incoterms`                                         varchar(4) DEFAULT NULL,
    `TransactionTaxClassification`                      varchar(1) NOT NULL,
    `ProductTaxClassificationBillToCountry`             varchar(1) NOT NULL,
    `ProductTaxClassificationBillFromCountry`           varchar(1) NOT NULL,
    `DefinedTaxClassification`                          varchar(1) NOT NULL,
    `AccountAssignmentGroup`                            varchar(2) NOT NULL,
    `ProductAccountAssignmentGroup`                     varchar(2) NOT NULL,
    `PaymentTerms`                                      varchar(4) NOT NULL,
    `DueCalculationBaseDate`                            date DEFAULT NULL,
    `PaymentDueDate`                                    date DEFAULT NULL,
    `NetPaymentDays`                                    int(3) DEFAULT NULL,
    `PaymentMethod`                                     varchar(1) NOT NULL,
    `Project`                                           int(16) DEFAULT NULL,
    `WBSElement`                                        int(8) DEFAULT NULL,
    `ItemBillingStatus`                                 varchar(2) DEFAULT NULL,
    `TaxCode`                                           varchar(1) DEFAULT NULL,
    `TaxRate`                                           float(6) DEFAULT NULL,
    `ItemBlockStatus`                                   tinyint(1) DEFAULT NULL,
    `ItemBillingBlockStatus`                            tinyint(1) DEFAULT NULL,
    `IsCancelled`                                       tinyint(1) DEFAULT NULL,
    `IsMarkedForDeletion`                               tinyint(1) DEFAULT NULL,
    
    PRIMARY KEY (`FreightAgreement`, `FreightAgreementItem`),
    
    CONSTRAINT `DataPlatformFreightAgreementItemData_fk` FOREIGN KEY (`FreightAgreement`) REFERENCES `data_platform_freight_agreement_header_data` (`FreightAgreement`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataSupplyChainRelationshipDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_supply_chain_relationship_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataSupplyChainRelationshipDeliveryPlantID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`) REFERENCES `data_platform_supply_chain_relationship_delivery_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataProductGroup_fk` FOREIGN KEY (`ProductGroup`) REFERENCES `data_platform_product_group_product_group_data` (`ProductGroup`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataDeliverToPlantTimeZone_fk` FOREIGN KEY (`DeliverToPlantTimeZone`) REFERENCES `data_platform_time_zone_time_zone_data` (`TimeZone`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataDeliverFromPlantTimeZone_fk` FOREIGN KEY (`DeliverFromPlantTimeZone`) REFERENCES `data_platform_time_zone_time_zone_data` (`TimeZone`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataDeliverFromPlantStorageLocation_fk` FOREIGN KEY (`DeliverFromParty`, `DeliverFromPlant`, `DeliverFromPlantStorageLocation`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataIncoterms_fk` FOREIGN KEY (`Incoterms`) REFERENCES `data_platform_incoterms_incoterms_data` (`Incoterms`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataPaymentMethod_fk` FOREIGN KEY (`PaymentMethod`) REFERENCES `data_platform_payment_method_payment_method_data` (`PaymentMethod`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataTaxCode_fk` FOREIGN KEY (`TaxCode`) REFERENCES `data_platform_tax_code_tax_code_data` (`TaxCode`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataCountryOfOrigin_fk` FOREIGN KEY (`CountryOfOrigin`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DataPlatformFreightAgreementItemDataCountryOfOriginLanguage_fk` FOREIGN KEY (`CountryOfOriginLanguage`) REFERENCES `data_platform_language_language_data` (`Language`),

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
