CREATE TABLE `data_platform_freight_agreement_header_data`
(
  `FreightAgreement`                          int(16) NOT NULL,
  `FreightAgreementDate`                      date NOT NULL,
  `FreightAgreementType`                      varchar(3) NOT NULL,
  `SupplyChainRelationshipID`                 int(16) NOT NULL,
  `SupplyChainRelationshipFreightID`          int(16) NOT NULL,
  `SupplyChainRelationshipFreightBillingID`   int(4) DEFAULT NULL,
  `SupplyChainRelationshipFreightPaymentID`   int(2) DEFAULT NULL,
  `Buyer`                                     int(12) NOT NULL,
  `Seller`                                    int(12) NOT NULL,
  `FreightPartner`                            int(12) NOT NULL,
  `FreightBillToParty`                        int(12) DEFAULT NULL,
  `FreightBillFromParty`                      int(12) DEFAULT NULL,
  `FreightBillToCountry`                      varchar(3) DEFAULT NULL,
  `FreightBillFromCountry`                    varchar(3) DEFAULT NULL,
  `FreightPayer`                              int(12) DEFAULT NULL,
  `FreightPayee`                              int(12) DEFAULT NULL,
  `CreationDate`                              date NOT NULL,
  `LastChangeDate`                            date NOT NULL,
  `ContractType`                              varchar(4) DEFAULT NULL,
  `FreightAgreementValidityStartDate`         date DEFAULT NULL,
  `FreightAgreementValidityEndDate`           date DEFAULT NULL,
  `InvoicePeriodStartDate`                    date DEFAULT NULL,
  `InvoicePeriodEndDate`                      date DEFAULT NULL,
  `HeaderBillingStatus`                       varchar(2) NOT NULL,
  `HeaderDocReferenceStatus`                  varchar(2) NOT NULL,
  `TransactionCurrency`                       varchar(5) NOT NULL,
  `PricingDate`                               date NOT NULL,
  `PriceDetnExchangeRate`                     float(8) DEFAULT NULL,
  `Incoterms`                                 varchar(4) DEFAULT NULL,
  `PaymentTerms`                              varchar(4) NOT NULL,
  `PaymentMethod`                             varchar(1) NOT NULL,
  `ReferenceDocument`                         int(16) DEFAULT NULL,
  `ReferenceDocumentItem`                     int(6) DEFAULT NULL,
  `AccountAssignmentGroup`                    varchar(2) NOT NULL,
  `AccountingExchangeRate`                    float(8) DEFAULT NULL,
  `InvoiceDocumentDate`                       date NOT NULL,
  `IsExportImport`                            tinyint(1) DEFAULT NULL,
  `HeaderText`                                varchar(200) DEFAULT NULL,
  `HeaderBlockStatus`                         tinyint(1) DEFAULT NULL,
  `HeaderBillingBlockStatus`                  tinyint(1) DEFAULT NULL,
  `IsCancelled`                               tinyint(1) DEFAULT NULL,
  `IsMarkedForDeletion`                       tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`FreightAgreement`),

    CONSTRAINT `DataPlatformFreightAgreementHeaderSupplyChainRelationshipID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `Buyer`, `Seller`) REFERENCES `data_platform_supply_chain_relationship_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
    CONSTRAINT `DataPlatformFreightAgreementHeaderSupplyChainRelationshipFreightID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipFreightID`, `Buyer`, `Seller`, `FreightPartner`) REFERENCES `data_platform_supply_chain_relationship_freight_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipFreightID`, `Buyer`, `Seller`, `FreightPartner`),
    CONSTRAINT `DataPlatformFreightAgreementHeaderSupplyChainRelationshipFreightBillingID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipFreightID`, `SupplyChainRelationshipFreightBillingID`, `Buyer`, `Seller`, `FreightPartner`, `FreightBillToParty`, `FreightBillFromParty`) REFERENCES `data_platform_supply_chain_relationship_freight_billing_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipFreightID`, `SupplyChainRelationshipFreightBillingID`, `Buyer`, `Seller`, `FreightPartner`, `FreightBillToParty`, `FreightBillFromParty`),
    CONSTRAINT `DataPlatformFreightAgreementHeaderSupplyChainRelationshipFreightPaymentID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipFreightID`, `SupplyChainRelationshipFreightBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `FreightPartner`, `FreightBillToParty`, `FreightBillFromParty`, `FreightPayer`, `FreightPayee`) REFERENCES `data_platform_supply_chain_relationship_freight_payment_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipFreightID`, `SupplyChainRelationshipFreightBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `FreightPartner`, `FreightBillToParty`, `FreightBillFromParty`, `FreightPayer`, `FreightPayee`),
    CONSTRAINT `DataPlatformFreightAgreementHeaderFreightBillToCountry_fk` FOREIGN KEY (`FreightBillToCountry`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DataPlatformFreightAgreementHeaderFreightBillFromCountry_fk` FOREIGN KEY (`FreightBillFromCountry`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DataPlatformFreightAgreementHeaderTransactionCurrency_fk` FOREIGN KEY (`TransactionCurrency`) REFERENCES `data_platform_currency_currency_data` (`Currency`),
    CONSTRAINT `DataPlatformFreightAgreementHeaderIncoterms_fk` FOREIGN KEY (`Incoterms`) REFERENCES `data_platform_incoterms_incoterms_data` (`Incoterms`),
    CONSTRAINT `DataPlatformFreightAgreementHeaderPaymentTerms_fk` FOREIGN KEY (`PaymentTerms`) REFERENCES `data_platform_payment_terms_payment_terms_data` (`PaymentTerms`),
    CONSTRAINT `DataPlatformFreightAgreementHeaderPaymentMethod_fk` FOREIGN KEY (`PaymentMethod`) REFERENCES `data_platform_payment_method_payment_method_data` (`PaymentMethod`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
